In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


## 1. Pandas
* 데이터 분석을 위한 고수준의 자료구조와 데이터분석도구를 제공
* Series: 1차원데이터
* DataFrame: 2차원 데이터

* list : []
* set : {}
* tuple : ()
* dictionary : { key:value }

##### Series

In [23]:
kakao = pd.Series([90000, 91000, 95000, 93000], index=['2019-0101','2019-0102','2019-0103', '2019-0104'])
kakao

2019-0101    90000
2019-0102    91000
2019-0103    95000
2019-0104    93000
dtype: int64

In [24]:
kakao['2019-0101']

90000

In [25]:
for i in kakao.index:
    print(i)
for i in kakao.values:
    print(i)

2019-0101
2019-0102
2019-0103
2019-0104
90000
91000
95000
93000


##### DataFrame

In [55]:
daeshin = { 'open': [11650, 11000, 12000, 12500],
            'high': [12000, 11450, 12200, 12600],
            'low': [11300, 10900, 11900, 12000],
            'close': [11800, 11300, 12100, 12400] 
           }
date_idx = [20190101, 20190102, 20190103, 20190104]
df= pd.DataFrame(daeshin, columns=['open', 'high', 'low', 'close'], index=date_idx)
df

open   high    low  close
20190101  11650  12000  11300  11800
20190102  11000  11450  10900  11300
20190103  12000  12200  11900  12100
20190104  12500  12600  12000  12400

In [57]:
samsung = [{'open':45000, 'high':50000, 'low':44000, 'close':48000},
           {'open':43000, 'high':49000, 'low':44000, 'close':47000},
           {'open':42000, 'high':48000, 'low':44000, 'close':46000},
           {'open':41000, 'high':47000, 'low':44000, 'close':45000}
          ]
date_idx = [20190101, 20190102, 20190103, 20190104]
df1 = pd.DataFrame(samsung, columns=['open','high','low','close'], index=date_idx)
df1

open   high    low  close
20190101  45000  50000  44000  48000
20190102  43000  49000  44000  47000
20190103  42000  48000  44000  46000
20190104  41000  47000  44000  45000

##### df.head(), df.tail(), df.info()

In [67]:
df.head()
df.tail()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 20190101 to 20190104
Data columns (total 4 columns):
open     4 non-null int64
high     4 non-null int64
low      4 non-null int64
close    4 non-null int64
dtypes: int64(4)
memory usage: 320.0 bytes


##### df.loc[], df.iloc[]

In [60]:
print(df['open']) #열 접근
print(df.loc[20190101]) #행 접근
print(df.iloc[0,1]) #행열 (숫자)접근

20190101    11650
20190102    11000
20190103    12000
20190104    12500
Name: open, dtype: int64
open     11650
high     12000
low      11300
close    11800
Name: 20190101, dtype: int64
12000


#####  df.query()

In [65]:
df1.query('open>42000')
df1[ (df1.open>42000)]

open   high    low  close
20190101  45000  50000  44000  48000
20190102  43000  49000  44000  47000

In [59]:
for i in df.columns:
    print(i)
for i in df.index:
    print(i)
for i in df.values:
    print(i)

open
high
low
close
20190101
20190102
20190103
20190104
[11650 12000 11300 11800]
[11000 11450 10900 11300]
[12000 12200 11900 12100]
[12500 12600 12000 12400]



##### df.drop()

In [83]:
print(df)
df_filtered = df.drop(['high', 'low'], axis=1)
print(df_filtered)
df.drop(['high', 'low'], axis=1, inplace=True)

           open   high    low  close
20190101  11650  12000  11300  11800
20190102  11000  11450  10900  11300
20190103  12000  12200  11900  12100
20190104  12500  12600  12000  12400
           open  close
20190101  11650  11800
20190102  11000  11300
20190103  12000  12100
20190104  12500  12400


##### Aggregates
* mean
* std
* median
* max
* min
* count
* nunique
* unique

In [91]:
df.describe().T

count     mean         std      min      25%      50%      75%      max
open     4.0  11787.5  630.310770  11000.0  11487.5  11825.0  12125.0  12500.0
close    4.0  11900.0  469.041576  11300.0  11675.0  11950.0  12175.0  12400.0

In [85]:
print(df.mean(), sep='\n')
print(df.std())
print(df.median())
print(df.max())
print(df.min())
print(df.count())

open     11787.5
close    11900.0
dtype: float64
open     630.310770
close    469.041576
dtype: float64
open     11825.0
close    11950.0
dtype: float64
open     12500
close    12400
dtype: int64
open     11000
close    11300
dtype: int64
open     4
close    4
dtype: int64


##### groupby()

##### pd.merge()

##### pd.concat()

##### pd.join()

## 데이터 접근

In [86]:
train = pd.read_csv("train_titanic.csv")

In [88]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [89]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


* Age항목에 대한 결측치 채울 필요 있음.(평균으로 채우기)
* Sex항목에 대한 female, male을 원핫인코딩을 해야함.

##### 필터

In [128]:
x_train = train[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]
x_train

Pclass     Sex   Age  SibSp  Parch
0         3    male  22.0      1      0
1         1  female  38.0      1      0
2         3  female  26.0      0      0
3         1  female  35.0      1      0
4         3    male  35.0      0      0
5         3    male   NaN      0      0
6         1    male  54.0      0      0
7         3    male   2.0      3      1
8         3  female  27.0      0      2
9         2  female  14.0      1      0
10        3  female   4.0      1      1
11        1  female  58.0      0      0
12        3    male  20.0      0      0
13        3    male  39.0      1      5
14        3  female  14.0      0      0
15        2  female  55.0      0      0
16        3    male   2.0      4      1
17        2    male   NaN      0      0
18        3  female  31.0      1      0
19        3  female   NaN      0      0
20        2    male  35.0      0      0
21        2    male  34.0      0      0
22        3  female  15.0      0      0
23        1    male  28.0      0      0
24        3  female   8.0      3      1
25        3  female  38.0      1      5
26        3    male   NaN      0      0
27        1    male  19.0      3      2
28        3  female   NaN      0      0
29        3    male   NaN      0      0
..      ...     ...   ...    ...    ...
861       2    male  21.0      1      0
862       1  female  48.0      0      0
863       3  female   NaN      8      2
864       2    male  24.0      0      0
865       2  female  42.0      0      0
866       2  female  27.0      1      0
867       1    male  31.0      0      0
868       3    male   NaN      0      0
869       3    male   4.0      1      1
870       3    male  26.0      0      0
871       1  female  47.0      1      1
872       1    male  33.0      0      0
873       3    male  47.0      0      0
874       2  female  28.0      1      0
875       3  female  15.0      0      0
876       3    male  20.0      0      0
877       3    male  19.0      0      0
878       3    male   NaN      0      0
879       1  female  56.0      0      1
880       2  female  25.0      0      1
881       3    male  33.0      0      0
882       3  female  22.0      0      0
883       2    male  28.0      0      0
884       3    male  25.0      0      0
885       3  female  39.0      0      5
886       2    male  27.0      0      0
887       1  female  19.0      0      0
888       3  female   NaN      1      2
889       1    male  26.0      0      0
890       3    male  32.0      0      0

[891 rows x 5 columns]

In [136]:
y_train = train[['Survived']]

##### 결측치 채우기

In [129]:
x_train['Age'].fillna(x_train['Age'].mean(), inplace=True)

/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py:5434: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [134]:
for i in range (0,891):
    if (x_train.iloc[i,1] == 'male'):
        x_train.iloc[i,1] = 0
    elif  (x_train.iloc[i,1] == 'female'):
        x_train.iloc[i,1] = 1 
    else:
        print('err')

/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
