In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 1. Pandas
* 데이터 분석을 위한 고수준의 자료구조와 데이터분석도구를 제공
* Series: 1차원데이터
* DataFrame: 2차원 데이터

* list : []
* set : {}
* tuple : ()
* dictionary : { key:value }

##### Series

In [20]:
kakao = pd.Series([90000, 91000, 95000, 93000], index=['2019-0101','2019-0102','2019-0103', '2019-0104'])
kakao

2019-0101    90000
2019-0102    91000
2019-0103    95000
2019-0104    93000
dtype: int64

In [21]:
kakao['2019-0101']

90000

In [26]:
for i in kakao.index:
    print(i)
for i in kakao.values:
    print(i)

2019-0101
2019-0102
2019-0103
2019-0104
90000
91000
95000
93000


##### DataFrame

##### 빈 데이터 프레임 만들기

In [28]:
df_all = pd.DataFrame(columns=['acc_x', 'acc_y'])

In [32]:
daeshin = { 'open': [11650, 11000, 12000, 12500],
            'high': [12000, 11450, 12200, 12600],
            'low': [11300, 10900, 11900, 12000],
            'close': [11800, 11300, 12100, 12400] 
           }
date_idx = [20190101, 20190102, 20190103, 20190104]
df= pd.DataFrame(daeshin, columns=['open', 'high', 'low', 'close'], index=date_idx)
df

open   high    low  close
20190101  11650  12000  11300  11800
20190102  11000  11450  10900  11300
20190103  12000  12200  11900  12100
20190104  12500  12600  12000  12400

In [33]:
samsung = [{'open':45000, 'high':50000, 'low':44000, 'close':48000},
           {'open':43000, 'high':49000, 'low':44000, 'close':47000},
           {'open':42000, 'high':48000, 'low':44000, 'close':46000},
           {'open':41000, 'high':47000, 'low':44000, 'close':45000}
          ]
date_idx = [20190101, 20190102, 20190103, 20190104]
df1 = pd.DataFrame(samsung, columns=['open','high','low','close'], index=date_idx)
df1

open   high    low  close
20190101  45000  50000  44000  48000
20190102  43000  49000  44000  47000
20190103  42000  48000  44000  46000
20190104  41000  47000  44000  45000

##### df.head(), df.tail(), df.info()

In [34]:
df.head()
df.tail()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 20190101 to 20190104
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   open    4 non-null      int64
 1   high    4 non-null      int64
 2   low     4 non-null      int64
 3   close   4 non-null      int64
dtypes: int64(4)
memory usage: 160.0 bytes


##### df.loc[], df.iloc[]

In [35]:
print(df['open']) #열 접근
print(df.loc[20190101]) #행 접근
print(df.iloc[0,1]) #행열 (숫자)접근

20190101    11650
20190102    11000
20190103    12000
20190104    12500
Name: open, dtype: int64
open     11650
high     12000
low      11300
close    11800
Name: 20190101, dtype: int64
12000


#####  df.query()

In [36]:
df1.query('open>42000')
df1[ (df1.open>42000)]

open   high    low  close
20190101  45000  50000  44000  48000
20190102  43000  49000  44000  47000

In [37]:
for i in df.columns:
    print(i)
for i in df.index:
    print(i)
for i in df.values:
    print(i)

open
high
low
close
20190101
20190102
20190103
20190104
[11650 12000 11300 11800]
[11000 11450 10900 11300]
[12000 12200 11900 12100]
[12500 12600 12000 12400]



##### df.drop()

In [38]:
print(df)
df_filtered = df.drop(['high', 'low'], axis=1)
print(df_filtered)
df.drop(['high', 'low'], axis=1, inplace=True)

           open   high    low  close
20190101  11650  12000  11300  11800
20190102  11000  11450  10900  11300
20190103  12000  12200  11900  12100
20190104  12500  12600  12000  12400
           open  close
20190101  11650  11800
20190102  11000  11300
20190103  12000  12100
20190104  12500  12400


##### Aggregates
* mean
* std
* median
* max
* min
* count
* nunique
* unique

In [39]:
df.describe().T

count     mean         std      min      25%      50%      75%      max
open     4.0  11787.5  630.310770  11000.0  11487.5  11825.0  12125.0  12500.0
close    4.0  11900.0  469.041576  11300.0  11675.0  11950.0  12175.0  12400.0

In [40]:
print(df.mean(), sep='\n')
print(df.std())
print(df.median())
print(df.max())
print(df.min())
print(df.count())

open     11787.5
close    11900.0
dtype: float64
open     630.310770
close    469.041576
dtype: float64
open     11825.0
close    11950.0
dtype: float64
open     12500
close    12400
dtype: int64
open     11000
close    11300
dtype: int64
open     4
close    4
dtype: int64


##### groupby()

##### pd.merge()

##### pd.concat(), append()

In [41]:
df.append(df)

open  close
20190101  11650  11800
20190102  11000  11300
20190103  12000  12100
20190104  12500  12400
20190101  11650  11800
20190102  11000  11300
20190103  12000  12100
20190104  12500  12400

In [ ]:
df = df.append(df, ignore_index=True)

##### 컬럼에 이름 넣기

In [49]:
df.columns = ['open', 'closes']
#dfs.index = ['h', 'a', 'n']

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   open    8 non-null      int64
 1   closes  8 non-null      int64
dtypes: int64(2)
memory usage: 256.0 bytes


##### 형 변환

In [52]:
df['open'] = df['open'].astype('float')

##### 인덱스 초기화

In [44]:
df.reset_index()

index   open  close
0      0  11650  11800
1      1  11000  11300
2      2  12000  12100
3      3  12500  12400
4      4  11650  11800
5      5  11000  11300
6      6  12000  12100
7      7  12500  12400

##### pd.join()

## 데이터 접근

In [ ]:
train = pd.read_csv("train_titanic.csv")

##### 텍스트파일 읽기

In [ ]:
df = pd.read_csv("hello.txt", sep=" ", header=None)

In [ ]:
train.head()

In [ ]:
train.info()

* Age항목에 대한 결측치 채울 필요 있음.(평균으로 채우기)
* Sex항목에 대한 female, male을 원핫인코딩을 해야함.

##### 필터

In [ ]:
x_train = train[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]
x_train

In [ ]:
y_train = train[['Survived']]

##### 결측치 채우기

In [ ]:
x_train['Age'].fillna(x_train['Age'].mean(), inplace=True)

In [ ]:
for i in range (0,891):
    if (x_train.iloc[i,1] == 'male'):
        x_train.iloc[i,1] = 0
    elif  (x_train.iloc[i,1] == 'female'):
        x_train.iloc[i,1] = 1 
    else:
        print('err')

##### 결측치 버리기

In [ ]:
#결측값이 들어있는 열 전체 삭제하기
x_train.dropna(axis=0)
#특정 행 또는 열을 대상으로 결측값이 들어있으면 제거
x_train['Age'].dropna(axis=0)